blog/urls.py
from django.urls import path
from .views import ProjectListView
from . import views

urlpatterns = [
    path('', ProjectListView.as_view(), name='blog-home'),
    path('client', views.client, name='blog-client'),
    path('user', views.user, name='blog-user'),
]

django_firm/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Client(models.Model):
    lastName = models.CharField(max_length=20)
    firstName = models.CharField(max_length=20)
    phoneNumber = models.CharField(max_length=10)
    firm = models.CharField(max_length=50)

    def __str__(self):
        return "Client :\n\t" + self.lastName.upper()

class Project(models.Model):
    name = models.CharField(max_length=100)
    duration = models.IntegerField()
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    client = models.ManyToManyField(Client)

    def __str__(self):
        return "Project :\n\t" + self.name 

class Task(models.Model):
    abstract = models.TextField()
    duration = models.IntegerField()
    startTime = models.TimeField()
    endTime = models.TimeField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return "Task :\n\t" + self.abstract

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField() #default required = True

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']
    
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Client, Project, Task

def home(request):
    context = {
        'projects': Project.objects.all(),
        'title': "Bogoss"
    }
    return render(request, 'blog/home.html', context)

class ProjectListView(ListView):
    model = Project
    template_name = 'blog/home.html' # default : <app>/<model>_<viewtype>.html
    context_object_name = 'projects'
    ordering = ['startDate'] # '-startDate' for an descending order

def client(request):
    return render(request, 'blog/client.html')

def user(request):
    return render(request, 'blog/user.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

def register(request):
    if (request.method == 'POST'):
        form = UserRegisterForm(request.POST)
        if (form.is_valid()):
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in!')
            return redirect('login')
    else:    
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    if (request.method == 'POST'):
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated !')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    {% if title %}
        <title>Aelo Corp - {{ title }}</title>
    {% else %}
        <title>Aelo Corp</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Aelo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                    </div>
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/client.html
{% extends "blog/base.html" %}
{% block content %}
  <project class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ client.lastName }} {{ client.firstName }}</a>
        <small class="text-muted">{{ client.phoneNumber }}</small>
      </div>
      <p class="article-content">{{ client.firm }}</p>
      {% for project in client.project %}
          <h2>Projects :</h2>
          <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;Title : {{ project.name }}</p>
          <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;Duration : {{ project.duration }} ({{ project.startDate | date:"F d, Y" }} -> {{ project.endDate | date:"F d, Y" }} )</p>
      {% endfor %}
      {% for task in client.task %}
          <h2>Tasks :</h2>
          <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;Abstract : {{ task.abstract }}</p>
          <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;Duration : {{ task.duration }} ( {{ task.startTime }} -> {{ task.endTime }} )</p>
      {% endfor %}
    </div>
  </project>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for project in projects %}
        <project class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <img class="rounded-circle article-img" src="{{ project.client.profile.image.url }}">
              <a class="mr-2" href="#">{{ project.name }}</a>
              <small class="text-muted">{{ project.startDate | date:"F d, Y" }} -> {{ project.endDate | date:"F d, Y" }}</small>
            </div>
            <h2>Clients :</h2>
            {% for client in project.client.in_bulk.values %}
              <h8>&nbsp;&nbsp;{{ client.id }}</h8>
              <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name : {{ client.lastName }} {{ client.firstName }}</p>
              <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Firm : {{ client.firm }}</p>
              <p class="article-content display">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Phone number : {{ client.phoneNumber }}</p>
              {% if client.task_set.first %}
                <h5>&nbsp;&nbsp;&nbsp;&nbsp;Tasks :</h5>
              {% endif %}
              {% for task in client.task_set.all %}
                  <h10>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ task.id }}</h10>
                  <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Abstract : {{ task.abstract }}</p>
                  <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Duration : {{ task.duration }} hours ( {{ task.startTime }} -> {{ task.endTime }} )</p>
              {% endfor %}
            {% endfor %}
          </div>
        </project>
    {% endfor %}
{% endblock content %}

blog/templates/blog/user.html
{% extends "blog/base.html" %}
{% block content %}
    {% for client in clients %}
        <project class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ client.lastName }} {{ client.firstName }}</a>
              <small class="text-muted">{{ client.phoneNumber }}</small>
            </div>
            <p class="article-content">{{ client.firm }}</p>
            {% for project in client.project %}
                <h2>Projects :</h2>
                <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;Title : {{ project.name }}</p>
          <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;Duration : {{ project.duration }} ({{ project.startDate | date:"F d, Y" }} -> {{ project.endDate | date:"F d, Y" }} )</p>
            {% endfor %}
            {% for task in client.task %}
                <h2>Tasks :</h2>
                <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;Abstract : {{ task.abstract }}</p>
                <p class="article-content">&nbsp;&nbsp;&nbsp;&nbsp;Duration : {{ task.duration }} ( {{ task.startTime }} -> {{ task.endTime }} )</p>
            {% endfor %}
          </div>
        </project>
    {% endfor %}
{% endblock content %}

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Log In</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content%}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
<h2>You have been logged out !</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}"">Log In Again</a>
        </small>
    </div>
{% endblock content%}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form | crispy }}
                {{ p_form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content%}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content%}